language: node_js
os:
    - linux
    - windows
    - osx
node_js:
    - "stable"
    - "6.9.1"
    - "5.12.0"
sudo: false
script:
    - npm test
after_success:
    - bash <(curl -s https://codecov.io/bash)
